version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${PORT_SERVER}:${PORT_SERVER_CONTAINER}"
    env_file:
      - .env  

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"    